#!/usr/bin/env zsh
#ask for sudo ath
sudo --validate
# Update the configs first
if [ -x "$(command -v upTermFiles)" ];then
 upTermFiles
fi
#update npm global packages
if [ -x "$(command -v npm)" ];then
  CURRENT=$(npm -v)
  LATEST=$(npm view npm version --silent)
  if [ "$CURRENT" != "$LATEST" ]; then
    sudo npm install -g npm@latest
  fi
  sudo npm up -g
fi
#update system
#remove unwanted packages
#clean cache
##dont ask for any other stuff other than
#password for sudo
if [ -x "$(command -v yay)" ]; then
  yay -Syu --noconfirm --sudoloop
  if [[ $(pacman -Qdtq|wc -l) > 0 ]];then
    sudo pacman -Rs $(pacman -Qdtq) --noconfirm
  fi
  yay -Scc --noconfirm
elif [ -x "$(command -v apt)" ]; then
  sudo apt update
  sudo apt dist-upgrade -y
  sudo apt autoremove -y
  sudo apt autoclean -y
fi
#update zsh plugins
source ~/.cache/antidote/antidote.zsh
antidote update
