#!/usr/bin/env zsh

BATTERY_ID="${BLOCK_INSTANCE}"
LOW_THRESHOLD=20
SOUND_FILE="$HOME/.config/sound_events/low_power.wav"
DEVICE_PATH=$(upower -e | grep "${BATTERY_ID}")

BATTERY_INFO=$(upower -i "$DEVICE_PATH")
read -r PERCENTAGE STATE <<<"$(echo "$BATTERY_INFO" | awk '
    /percentage:/ { p = $2 }
    /state:/      { s = $2 }
    END           { print p, s }
')"
echo "$PERCENTAGE"
if [[ "$STATE" != "charging" ]] && [[ "${PERCENTAGE/\%}" -lt "$LOW_THRESHOLD" ]]; then
    aplay "$SOUND_FILE" &>/dev/null &!
fi
