#!/usr/bin/env zsh

BATTERY_ID="${BLOCK_INSTANCE}"
LOW_THRESHOLD=20
SOUND_FILE="$HOME/.config/sound_events/low_power.wav"
DEVICE_PATH=$(upower -e | grep "${BATTERY_ID}")
if [[ -z "$DEVICE_PATH" ]]; then
    exit 1
fi
BATTERY_INFO=$(upower -i "$DEVICE_PATH")
read -r PERCENTAGE STATE <<<"$(echo "$BATTERY_INFO" | awk '
    /percentage:/ { p = $2 }
    /charging/      { s = "true" }
    END           { print p, s }
')"
echo "$PERCENTAGE $STATE"
if [[ "$STATE" != "true"  ]] && [[ "${PERCENTAGE/\%}" -lt "$LOW_THRESHOLD" ]]; then
    aplay "$SOUND_FILE" &>/dev/null &!
fi
