#!/usr/bin/env zsh
function bars_output() {
  ((bars=$_con_state/25))
  case $bars in
    4)echo "▂▄▆▉";;
    3)echo "▂▄▆";;
    2)echo "▂▄";;
    1)echo "▂";;
    *)echo "ERR";;
  esac
}
if [[ $BLOCK_BUTTON == 2 ]];then
  xterm -e nmtui
fi
_con_device=`nmcli device status|awk '$3=="connected" {print $1}'`
if [ ! -z $_con_device ];then
  _con_info=`nmcli device show $_con_device`
  _con_type=`echo $_con_info|awk '$1 ~ "TYPE" {print $2}'`
  if [[ $_con_type == "wifi" ]];then
    _con_state=`echo $_con_info|awk '$1 ~ "STATE"{print ($2+0)}'`
    echo -n "$_con_device: "
    bars_output
  else
    echo "$_con_type"
  fi
else
  echo "NET ERR"
fi
