#!/usr/bin/env zsh

if [[ "$BLOCK_BUTTON" == "2" ]]; then
    alacritty -e nmtui &
fi

connection_info=$(nmcli -t -f TYPE,DEVICE,NAME c s --active | head -n1)

if [[ -z "$connection_info" ]]; then
    echo "Disconnected"
fi

IFS=':' read -r con_type device ssid <<<"$connection_info"

case "$con_type" in
    "wifi"|"802-11-wireless")
        signal_strength=$(nmcli -t -f IN-USE,SIGNAL dev wifi list | grep '^*' | cut -d: -f2)
        local bars=$(( signal_strength / 25 ))
        local signal_icon

        case $bars in
            4) signal_icon="▂▄▆▉" ;;
            3) signal_icon="▂▄▆ " ;;
            2) signal_icon="▂▄  " ;;
            1) signal_icon="▂   " ;;
            *) signal_icon="    " ;;
        esac

        echo "$ssid $signal_icon"
        ;;
    "ethernet")
        echo "$device"
        ;;
    *)
        echo "$ssid"
        ;;
esac
