hl.on("hyprland.start", function ()
  hl.exec_cmd("systemctl --user start hyprpolkitagent")
  hl.exec_cmd("sh ~/.config/hypr/hyprportal.sh")
  hl.exec_cmd("dunst --config ~/.config/dunst/dunstrc")
  hl.exec_cmd("wl-paste --type text --watch cliphist store")
  hl.exec_cmd("wl-paste --type image --watch cliphist store")
  hl.exec_cmd("blueman-applet")
  hl.exec_cmd("waybar > ~/.cache/waybar.log 2>&1")
  hl.exec_cmd("firefox")
end)
