#!/bin/zsh
comphelp() {
    echo "Composition Manager:"
    echo "   (re)start: COMP"
    echo "   stop:      COMP -s"
    echo "              returns 0 if composition manager is running, else 1"
    exit
}
stopcomp() {
    killall xcompmgr
}
startcomp() {
    stopcomp
    xcompmgr -c -C -t-5 -l-5 -r4 -o.5 &
    exit
}
case "$1" in
    "")   startcomp ;;
    "-s") stopcomp; exit ;;
    *)    comphelp ;;
esac
