#!/bin/bash
# Fast kill -9 for one or more apps
if [ "$1" ];then
  IFS=$'\n'
  res=( $(pgrep $1) )
  if [ ! -z "$res" ];then
    echo -e "[$1]\n[Results]\n~~~~~~\n"
    for ((i=0;i<${#res[@]};i++));do
      echo -e $(pmap ${res[$i]}|head -n 1|awk '{print $1$2}') $(pmap ${res[$i]}|tail -1|awk '$1=int($2/1024)"mb"{print $1}')
    done
    echo -e "\n~~~~~~\n[KILL]?(?)! [Y/N]?"
    read -s r
    if [[ "$r" =~ ^([yY][eE][sS]|[yY])+$ ]];then
      kill -9 ${res[@]}
    fi
  else
    echo "No Process with name $1"
  fi
else
  echo "No Input"
fi
