#!/bin/zsh
# Fast kill -9 for one or more apps
function main(){
  local IFS=$'\n'
  local _s=""
  if [ "$2" ]; then
    _s="$2"
  else
    _s="$1"
  fi
  # Allow user to use pgrep option
  local res=( $(pgrep $1 $2) )
  if [ ! -z "$res" ];then
    echo -e "[$_s]\n[Results]\n~~~~~~~\n"
    # Print each pid ram usage in mb and cmd
    for i in $res;do
      local _name=$(ps -p $i -o cmd|tail -1)
      local _mem=$(pmap $i|tail -1|awk '{$1=int($2/1024);print $1}')
      printf "[%6d] %5dmb \e[32m%s\e[0m\n" $i $_mem $_name
    done
    # Ask the user before terminating the process
    echo -e "\n~~~~~~~\n[KILL THOSE ${#res[@]}]?(?)! [Y/N]?"
    read -s r
    if [[ "$r" =~ ^([yY][eE][sS]|[yY])+$ ]];then
      kill -9 ${res[@]}
    fi
  else
    echo "No Process with name $_s"
  fi
}
# Only check for 1 argument
if [ "$1" ];then
 main $@
else
  echo "No Input"
fi
