#!/usr/bin/env bash
#
# DO NOT USE THIS IF YOU DONT KNOW WHAT ITS DOING
# THERE ARE NO SAFETY CHECKS FOR THE DATA YOU ARE PASSING
# SO YOU MAY END UP LOSING SOME STUFF!
#
# Quick script to fix the images on each folder
# and also fix the thumb files
#
# Rename all images to 1 digit and concerts everything to jpg
# Checks for png JPEG jpeg JPG and converts them to jpg
# Removes stupid thumbs.db files
# Fixes thumb folder if its thumbs or n instead of m...
#
rnrm(){
  for f in *;do
    #check if it contains capital letters
    #change everything to lower case
    _tmp=${f,,}
    if [[ $f =~ [[:upper:]] ]];then
      mv "$f" "$_tmp"
    fi
    if [ ${f: -5} == ".jpeg" ] || [ ${f: -5} == ".JPEG" ];then
      mv "${_tmp}" "${_tmp/jpeg/jpg}"
    elif [ ${f: -4} == ".png" ];then
      mogrify -format jpg -quality 100 "$_tmp"
      rm -fv "$_tmp"
    fi
    unset _tmp
  done
  find . -maxdepth 1 -iname 'thumbs.db' -exec rm -fv {} +
  qdr -d 1 -f *.jpg
}
printf "\33[1;36mStarting from $1 Folder\033[0m\n"
cd $1
rnrm
printf "\33[1;36mGoing to $1/thumb Folder\033[0m\n"
if [ -d "thumb" ];then
  cd thumb
  rnrm
elif [ -d "thumbs" ];then
  mv thumbs thumb
  cd thumb
  rnrm
elif [ -d "thunbs" ];then
  mv thunbs thumb
  cd thumb
  rnrm
elif [ -d "thunb" ];then
  mv thunb thumb
  cd thumb
  rnrm
else
  printf "\033[1;31mThumb not found!\nEither different name or thumb missing(again!)\033[0m\n"
fi
