#!/usr/bin/env zsh
# Update the configs first
if [ -x "$(command -v upTermFiles)" ];then
 upTermFiles 
fi
#update nvim plugins
nvim -c "cal dein#update()" +qa!
#update zsh plugins
antibody update
#update npm global packages
if [ -x "$(command -v npm)" ];then
  npm i -g npm
  npm up -g
fi
#update system
#remove unwanted packages
#clean cache
##dont ask for any other stuff other than
#password for sudo
if [ -x "$(command -v yay)" ]; then
  yay -Syu --noconfirm --sudoloop
  sudo pacman -Rs $(pacman -Qdtq) --noconfirm
  yay -Scc --noconfirm
elif [ -x "$(command -v apt)" ]; then
  sudo apt update
  sudo apt dist-upgrade -y
  sudo apt autoremove -y
  sudo apt autoclean -y
fi
