#!/usr/bin/env zsh
#You need to install optipng and jpegoptim
#Errors will not be reported... So watch out for that...
q=90
if [[ ! -z $1 ]] && [[ ! "$1" =~ '^[0-9]+$' ]] && [ $1 -ge 1 ] && [ $1 -le 100 ];then
  q=$1
fi
echo "JPEG Quality: $q"
IFS=$'\n'
img=(`find . -iname "*.png" -o -iname "*.jpg" -o -iname "*.jpeg"`)

echo "$img"
function image {
  fname=${img[$1]##*/}
  fext=${fname##*.}
  size=$(stat --printf="%s" ${img[$1]}) #gets image size before compress
  echo -n "[$(( $1 + 1 ))/${#img[@]}]${img[$1]}"
  if [[ ${fext,,} == "png" ]];then
    optipng -o7 -strip all "${img[$1]}" > /dev/null 2>&1 #hide output
  else
    jpegoptim -f --all-progressive --max=$q "${img[$1]}" > /dev/null 2>&1 #hide output
  fi
  size2=$(stat --printf="%s" ${img[$1]}) #gets image size after the compress
  fsize=$(( $size - $size2 )) #calculates size old - new
  echo " [(Old) $size - (New) $size2 = $fsize]" #This is the final output before it goes to the next one
}
for (( i=1; i<=${#img[@]}; i++ )); do
  image $i
done
