#!/usr/bin/env zsh
#ask for sudo ath
sudo --validate
# Update the configs first
if [ -x "$(command -v upTermFiles)" ];then
 upTermFiles
fi
#keep sudo ath :)
sudo --validate
#update nvim plugins
nvim -c "cal dein#update()" +qa!
#update zsh plugins
antibody update
#update npm global packages
if [ -x "$(command -v npm)" ];then
  #check if there is npm in the outdated list
  #and then update npm
  _up_npm="$(sudo npm out -g)"
  if [[ $_up_npm =~ "npm" ]];then
    sudo npm i -g npm
  fi
  npm up -g
fi
#update system
#remove unwanted packages
#clean cache
##dont ask for any other stuff other than
#password for sudo
if [ -x "$(command -v yay)" ]; then
  yay -Syu --noconfirm --sudoloop
  if [[ $(pacman -Qdtq|wc -l) > 0 ]];then
    sudo pacman -Rs $(pacman -Qdtq) --noconfirm
  fi
  yay -Scc --noconfirm
elif [ -x "$(command -v apt)" ]; then
  sudo apt update
  sudo apt dist-upgrade -y
  sudo apt autoremove -y
  sudo apt autoclean -y
fi
