#!/bin/bash
echo "PORT: $1"
echo "MODE: $2"
echo "WIDTH: $3"
echo "HEIGHT: $4"
echo "RATE: $5"
read -p "Does this mode look right? " REPLY
if [[ $REPLY =~ ^[Yy]$ ]]; then
  MODE=`cvt12 $3 $4 $5 -b|awk 'END{$1=$2="";print $0}'`
  echo "MODE: $MODE"
  xrandr --newmode "$2" $MODE
  xrandr --addmode "$1" "$2"
  xrandr --output "$1" --mode "$2"
fi
