[opener]
#-------------------------------------------
# Websites
#-------------------------------------------
firefox = [
  { run = "firefox %s", orphan = true, desc = "Firefox" }
]

#-------------------------------------------
# Misc
#-------------------------------------------
exec = [
  { run = "%s1", orphan = true, desc = "Execute" }
]

man = [
  { run = "man %s1", block = true, desc = "Man page" }
]
wine_run = [
  { run = "wine_run %s", orphan = true, desc = "wine_run" }
]
proton = [
  { run = "proton %s", orphan = true, desc = "proton" }
]
wine = [
  { run = "wine %s", orphan = true, desc = "wine" }
]
make = [
  { run = "make", block = true, desc = "Make" }
]

#-------------------------------------------
# Code
#-------------------------------------------
python = [
  { run = "python %s1", block = true, desc = "Run Python" }
]
perl = [
  { run = "perl %s1", block = true, desc = "Run Perl" }
]
ruby = [
  { run = "ruby %s1", block = true, desc = "Run Ruby" }
]
node = [
  { run = "node %s1", block = true, desc = "Run Node" }
]
php = [
  { run = "php %s1", block = true, desc = "Run PHP" }
]

#-------------------------------------------
# Media
#-------------------------------------------
vlc = [
  { run = "vlc %s", orphan = true, desc = "VLC" }
]

#-------------------------------------------
# Documents
#-------------------------------------------
libreoffice = [
  { run = "libreoffice %s", orphan = true, desc = "LibreOffice" }
]

#-------------------------------------------
# Image Viewing
#-------------------------------------------
inkscape = [
  { run = "inkscape %s", orphan = true, desc = "Inkscape" }
]
display = [
  { run = "display %s", orphan = true, desc = "Display" }
]
imv = [
  { run = "imv %s", orphan = true, desc = "imv" }
]
gimp = [
  { run = "gimp %s", orphan = true, desc = "GIMP" }
]

#-------------------------------------------
# Archives
#-------------------------------------------
extract_7z = [
  { run = "7z -p x %s -aoa", block = true, desc = "Extract 7z" }
]
extract_tar = [
  { run = "for file in %s; do tar vvxf \"$file\"; done", block = true, desc = "Extract Tar" }
]
extract_rar = [
  { run = "for file in %s; do unrar x \"$file\"; done", block = true, desc = "Extract RAR" }
]

#-------------------------------------------
# Default option
#-------------------------------------------
nvim = [
  { run = "nvim %s", block = true, desc = "Neovim" }
]


[open]
rules = [
  # Websites
  { url = "*.{htm,html}", use = "firefox" },

  # Executables
  { url = "{*.exe,*.EXE,*.msi,*.MSI,}", use = [ "wine_run", "proton", "wine" ] },
  { mime = "application/*executable*", use = "exec" },
  { mime = "*shell*", use = "exec" },


  # Misc
  { url = "*.1", use = "man" },
  { url = "{Makefile,makefile}", use = "make" },

  # Code
  { url = "*.py", use = "python" },
  { url = "*.pl", use = "perl" },
  { url = "*.rb", use = "ruby" },
  { url = "*.js", use = "node" },
  { url = "*.php", use = "php" },

  # Media
  { mime = "audio/*", use = "vlc" },
  { mime = "video/*", use = "vlc" },

  # Documents
  { url = "*.pdf", use = "firefox" },
  { url = "*.{ppt,pptx,odf,odg,odp,ods,odt,doc,docx,sxc,xls,xlsx,xlt,xlw,gnm,gnumeric}", use = "libreoffice" },

  # Image Viewing
  { mime = "image/svg+xml", use = [ "inkscape", "display" ] },
  { mime = "image/*", use = [ "imv", "gimp" ] },
  { url = "*.xcf", use = "gimp" },

  # Archives
  { url = "*.{7z,zip}", use = "extract_7z" },
  { url = "*.{tar,gz,bz2,xz}", use = "extract_tar" },
  { url = "*.rar", use = "extract_rar" },

  # Fallback
  { url = "*", use = "nvim" }
]
