#!/usr/bin/zsh

#if first arg is number kill section with that number
if [[ $1  == [0-9] ]]; then
  tmux kill-session -t $1
#if first arg is 's' then kill the whole server
elif [[ $1 = "s" ]]; then
  tmux kill-server
#if there is no arg kill current section
elif [[ $1 = "" ]]; then
  if [[ $TMUX_PANE = "" ]]; then
    echo "You can not kill what you can not see..."
  else
    tmux kill-session -t $(echo $TMUX_PANE|tr -dc '0-9')
  fi
else
  echo "Press 's' to kill Server Or a number to kill that Section"
fi
