[terminal]
shell = { program = "/usr/bin/tmux", args = ["new-session"] }

[env]
TERM = "alacritty-direct"

[window]
padding = { x = 0, y = 0 }

[scrolling]
history = 10000

[font]
normal = { family = "Hack", style = "Regular" }
bold = { family = "Hack", style = "Bold" }
italic = { family = "Hack", style = "Italic" }
size = 9

[colors.primary]
background = "#24283b"
foreground = "#c0caf5"

[colors.cursor]
text = "#24283b"
cursor = "#c0caf5"

[colors.normal]
black = "#1d202f"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#a9b1d6"

[colors.bright]
black = "#414868"
red = "#f7768e"
green = "#9ece6a"
yellow = "#e0af68"
blue = "#7aa2f7"
magenta = "#bb9af7"
cyan = "#7dcfff"
white = "#c0caf5"
