#!/usr/bin/zsh
# Fast kill -9  to one or more apps
if [ "$1" ];then
  IFS=$'\n'       # make newlines the only separator
  res=($(ps ax|grep $1|grep -v "grep"|awk '{$2=$3=$4="";print $0}'))
  if [ ! -z "$res" ];then
   for ((i=1;i<=${#res[@]};i++));do
     res[$i]="$(echo $res[$i]|awk '{print $1}') $(pmap -x $(echo $res[$i]|awk '{print $1}')|grep 'total kB'|awk '$3 ~/[0-9\.]/ { $3 = int($3 / 1024) "mb"} {print $3}') $(echo $res[$i]|awk '{print $2}')"
   done
    echo -e "[$1]\n[Results]\n~~~~~~\n$(echo "$res"|awk '{print $2 " " $3}')\n~~~~~~\n[KILL]?(?)! [Y/N]?"
    read -s r
    if [[ "$r" =~ ^([yY][eE][sS]|[yY])+$ ]];then
      echo ""
      kill -9 $(echo "$res"|awk '{print $1}')
    fi
  else
    echo "No Process with name $1"
  fi
else
  echo "No Input"
fi
