#!/usr/bin/zsh
if [ $1 ];then
  res=$(ps cax|grep $1|awk '{print $NF}')
  echo  "[$1]\n[Results]\n~~~~~~\n$res\n~~~~~~\n[KILL]?(?)! [Y/N]?"
  read -s r
  if [[ "$r" =~ ^([yY][eE][sS]|[yY])+$ ]];then
    echo ""
    kill -9 $(ps cax|grep $1|awk '{print $1}')
  fi
else
  echo "No Input"
fi
