#!/bin/sh
h=$HOME
folders=(/.config/i3 /.config/nvim /.config/ranger /.zshf )
files=(/.zshrc /.Xresources)
for  d in ${folders[@]};do
  echo $h$d/* to /root$d
  #remove old files first
  sudo rm -rf $h$d/*
  #then add new
  sudo cp -rf $h$d/* /root$d
done
for f in ${files[@]};do
  echo $h$f to /root$f
  sudo cp -f $h$f /root$f
done
#finaly remore old plugins install new update plugins and upgrade plug then close
sudo nvim +PlugClean +PlugInstall +PlugUpgrade +PlugUpdate +qa!
